In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3],dtype=complex)
a

array([1.+0.j, 2.+0.j, 3.+0.j])

In [3]:
x=np.array([1,2,3],dtype=np.float)
x.dtype

dtype('float64')

In [4]:
#Indexing

In [5]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr1[0]

1

In [7]:
arr1[9]

10

In [9]:
arr1[-1]

10

In [10]:
#slicing

In [11]:
arr1[1:5]

array([2, 3, 4, 5])

In [12]:
#syntx[start,stop(not included),step]

In [13]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr1[0]=11
arr1

array([11,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
#broadcasting
#it is assigning a grp of values with same numbers

In [16]:
arr1[0:3]=0
arr1

array([ 0,  0,  0,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr1[0:3]=[1,2,3]

In [18]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr2=np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr2[0]

array([1, 2, 3])

In [21]:
arr2[-1]

array([7, 8, 9])

In [23]:
arr2[0][1]#this is not recommended

2

In [24]:
arr2[0,1]

2

In [25]:
arr2[0:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
arr5=np.arange(9)

In [27]:
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
##conditional selection

In [31]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr1>2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [33]:
arr1[arr1>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
arr1[(arr1>2) & (arr1<9)]

array([3, 4, 5, 6, 7, 8])

In [36]:
arr1[(arr1==2) | (arr1<9)]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
## Operations

In [38]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr1+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
arr1-arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
arr1*arr1

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [42]:
arr1-(arr1/2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [43]:
arr1*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [44]:
[1,2,3,4]*2
#inlist it is concatinated

[1, 2, 3, 4, 1, 2, 3, 4]

In [45]:
arr1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [46]:
arr1**100

array([          1,           0,  -818408495,           0, -1971132175,
                 0,  1027218017,           0, -1426542431,           0],
      dtype=int32)

In [47]:
#metods

In [49]:
#np.sqrt()
sqrt1=np.sqrt(np.array([1,4,9]))
sqrt1

array([1., 2., 3.])

In [50]:
#astype()
sqrt1.astype('int32')

array([1, 2, 3])

In [52]:
sqrt1.astype('str')

array(['1.0', '2.0', '3.0'], dtype='<U32')

In [53]:
np.exp(arr1) #e**value

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [54]:
np.sin(np.array([90,180]))

array([ 0.89399666, -0.80115264])

In [55]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
arr4=arr1*90

In [57]:
arr4

array([ 90, 180, 270, 360, 450, 540, 630, 720, 810, 900])

In [58]:
np.sin(arr4*np.pi/180)

array([ 1.0000000e+00,  1.2246468e-16, -1.0000000e+00, -2.4492936e-16,
        1.0000000e+00,  3.6739404e-16, -1.0000000e+00, -4.8985872e-16,
        1.0000000e+00,  6.1232340e-16])

In [59]:
np.sum(arr1)

55

In [60]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr2*5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
np.multiply(arr2,arr2) #element by multiplication

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [63]:
np.dot(arr2,arr2)#matrix multiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [64]:
np.linalg.det(arr2)#determinent

-9.51619735392994e-16

In [65]:
np.linalg.inv(arr2)#inverse

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])