# Assignment

Import numpy as np

In [16]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
l = [1,2,3,4,5]
np_array = np.array(l)
np_array

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
mat = np.arange(1,10)
mat=mat.reshape(3,3)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [4]:
mat_1 = np.arange(1,18,2)
mat_1 = mat_1.reshape(3,3)
mat_1

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [15]:
l_1 = np.random.rand(10)*10
print(l_1)

[8.39432658 4.1842949  8.10114697 1.840997   3.52526079 8.11732884
 9.97443448 8.56276858 5.24009501 7.30436848]


Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [14]:
array = np.array([1,2,3,4,5])
array = array.reshape(5,1)
array

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [13]:
array.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [12]:
l = np.random.rand(10)
l[[2,3,8]]

array([0.42403923, 0.20991826, 0.05554764])

Print alternate elements of that array

In [9]:
l[::2]

array([0.08715876, 0.16939538, 0.02292297, 0.84016153, 0.32374664])

Change last 3 elements into 100 using broadcasting and print

In [10]:
l[7:] = 100
l

array([8.71587616e-02, 9.86362285e-01, 1.69395381e-01, 2.21154694e-01,
       2.29229722e-02, 8.41812884e-01, 8.40161528e-01, 1.00000000e+02,
       1.00000000e+02, 1.00000000e+02])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [11]:
arr = np.arange(1,26)
arr = arr.reshape(5,5)
print(arr[1:4,1:4])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
